FROM rocm/vllm-dev:rocm7.2_navi_ubuntu24.04_py3.12_pytorch_2.9_vllm_0.14.0rc0

RUN apt-get update \
    && apt-get install -y libgl1 \
    && rm -rf /var/lib/apt/lists/*

ENV PYTHONUNBUFFERED=1
ENV PYTHONDONTWRITEBYTECODE=1
ENV PADDLE_PDX_DISABLE_MODEL_SOURCE_CHECK=True

WORKDIR /workspace/PaddleX
COPY . /workspace/PaddleX

RUN --mount=type=cache,target=/root/.cache/pip \
    python -m pip install . \
    && python -m pip install --force-reinstall --no-cache-dir "numpy==2.2.6" "scikit-image==0.25.2"

EXPOSE 8080

CMD ["paddlex_genai_server", "--model_name", "PaddleOCR-VL-1.5-0.9B", "--host", "0.0.0.0", "--port", "8080", "--backend", "vllm"]
